### ISSUE TITLE
Music kit doubling

### ISSUE THREAD

**Issue by YongkyA23** [rogeraabbccdd/CSGO-MVP#29]
How to automatically turn off the official music kit when we turn on the custom music kit?

**Comment by crashzk** [comment]
Apparently the plugin already does this.

https://github.com/rogeraabbccdd/CSGO-MVP/blob/0e0c0819e669f63deaa4dd64dce1f3669aa8039a/addons/sourcemod/scripting/kento_mvp.sp#L161-L163

**Comment by SanjaySRocks** [comment]
same issue facing. how to fix it.

**Comment by rogeraabbccdd** [comment]
Fixed.

**Comment by crashzk** [comment]
@rogeraabbccdd this problem still occurs in version `1.12`.

I have a standard valve music kit activated for my profile, I bought it on the steam market. If I choose an MVP both songs still play when I'm MVP.

Is there any way to stop playing the one with MVP from Valve's music kit and play only the one from the MVP plugin?
